apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - master-ntp-machineconfig.yaml
#c2VydmVyIDE5MC4xNzAuMjAuMTEzIGlidXJzdCBwcmVmZXIKCmRyaWZ0ZmlsZSAvdmFyL2xpYi9jaHJvbnkvZHJpZnQKbWFrZXN0ZXAgMS4wIDMKcnRjc3luYwpsb2dkaXIgL3Zhci9sb2cvY2hyb255Cg==