apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - pvc.yaml
  - serviceaccount.yaml
  - cronjob.yaml
  - rbac/clusterrole-etcd-backup.yaml
  - rbac/clusterrolebinding-etcd-backup.yaml
  - rbac/clusterrole-etcd-backup-debug.yaml
  - rbac/clusterrolebinding-etcd-backup-debug.yaml

