apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - pvc.yaml
  - serviceaccount.yaml
  - cronjob.yaml
  - rbac/clusterrole.yaml
  - rbac/clusterrolebinding.yaml
  - rbac/debug-clusterrole.yaml
  - rbac/debug-clusterrolebinding.yaml
